---
title: "aoc-2021-day11"
author: "parmsam"
date: "12/18/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(stringr)
library(here)
library(purrr)
library(glue)
```

# Q1: 
```{r}
data1 <- read_csv(here("input", "input-d11-example.txt"), col_names =FALSE)
# data1 <- read_csv(here("input", "input-d11-1.txt"), col_names =FALSE)

dumboOct <- function(df, column, steps) {
   for(i in 1:steps){
    # df <- df + str_dup("1",nchar(data1$X1)[[1]]) %>% as.numeric()
     df[[column]] <- df[[column]] + 1
   }
  return(df)
}

split_long <- function(df, sep1=""){
  data1_long <- df %>% 
    mutate(row = row_number(), .before = everything() ) %>% 
    separate(X1, into = 0:nchar(data1[1,]) %>% str_c("X",.), sep= sep1) %>% 
    select(-X0) %>% 
    pivot_longer(cols = X1:X10, names_to = "column") %>%
    mutate(column = as.numeric(str_remove(column, "X"))) %>%
    mutate(value = as.numeric(value))
  return(data1_long)
}

flashOct <- function(df){
  df 
}

data1_long <- split_long(data1)

dumboOct(data1_long, column = "value", steps = 2)
```
# Q2: 
```{r}

  
```

